# Generated by Django 5.2 on 2025-05-13 12:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_rename_name_appointment_date_set_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='appointment',
            name='contact_email',
            field=models.EmailField(blank=True, max_length=500, null=True),
        ),
    ]
