# Generated by Django 5.2 on 2025-05-13 13:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_appointment_contact_email'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='appointment',
            name='contact_email',
        ),
        migrations.RemoveField(
            model_name='appointment',
            name='first_name',
        ),
        migrations.RemoveField(
            model_name='appointment',
            name='last_name',
        ),
        migrations.RemoveField(
            model_name='appointment',
            name='phone_number',
        ),
    ]
