# Generated by Django 5.2 on 2025-05-22 06:50

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0010_busydate_busytime'),
    ]

    operations = [
        migrations.CreateModel(
            name='BusySlots',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
            ],
        ),
        migrations.CreateModel(
            name='TimeSlot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('time_range', models.CharField(max_length=50)),
                ('busy_slot', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='time_slots', to='api.busyslots')),
            ],
        ),
        migrations.DeleteModel(
            name='BusyDate',
        ),
        migrations.DeleteModel(
            name='BusyTime',
        ),
    ]
