# Generated by Django 5.2 on 2025-05-22 07:47

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0011_busyslots_timeslot_delete_busydate_delete_busytime'),
    ]

    operations = [
        migrations.AlterField(
            model_name='timeslot',
            name='busy_slot',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tislots', to='api.busyslots'),
        ),
    ]
