# Generated by Django 5.2 on 2025-05-22 08:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0012_alter_timeslot_busy_slot'),
    ]

    operations = [
        migrations.CreateModel(
            name='AdminAvailability',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('slot_one', models.BooleanField(default=True, verbose_name='7:00 - 8:30 AM')),
                ('slot_two', models.BooleanField(default=True, verbose_name='8:30 - 10:00 AM')),
                ('slot_three', models.BooleanField(default=True, verbose_name='10:00 - 11:30 AM')),
                ('slot_four', models.BooleanField(default=True, verbose_name='1:00 - 2:30 PM')),
                ('slot_five', models.BooleanField(default=True, verbose_name='2:30 - 4:00 PM')),
            ],
        ),
        migrations.RemoveField(
            model_name='timeslot',
            name='busy_slot',
        ),
        migrations.DeleteModel(
            name='BusySlots',
        ),
        migrations.DeleteModel(
            name='TimeSlot',
        ),
    ]
