# Generated by Django 5.2 on 2025-05-22 09:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0013_adminavailability_remove_timeslot_busy_slot_and_more'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='AdminAvailability',
            new_name='Unvailability',
        ),
    ]
